class Transaction {
  /// id - the unique id of the transaction generated by code
  /// title - title/name of the transaction
  /// amount - amount of the transaction
  /// dateOfTransaction - the date of transaction
  /// tags - type of transaction

  final String id;
  final String title;
  final double amount;
  final DateTime dateOfTransaction;
  final List<String> tags;

  Transaction(
      this.id, this.title, this.amount, this.dateOfTransaction, this.tags);
}
